info:
  component: Edge Server
spring:
  application:
    name: gateway-service

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false

zuul:
  routes:
    customer:
      path: /api/**
      serviceId: recipe-service

#ribbon:
#  eureka:
#    enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/
    registerWithEureka: false

server:
  port: 8765

management:
  security:
    enabled: false